
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmzlkfwxeghvlgtilzjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttemxrZnd4ZWdodmxndGlsempoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDMyMzUsImV4cCI6MjA2MzM3OTIzNX0.TZX4YRAyA00ht6UVBrPjJinXx8t6rfbd1jdryMaMcTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single supabase client for the entire application
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage, // Direct reference, don't use typeof window check
    storageKey: 'supabase-auth-token'
  }
});

// Prevent multiple instances warning by disabling the warning in development
if (process.env.NODE_ENV === 'development') {
  // @ts-ignore
  window.__SUPABASE_AUTH_PROVIDERS_SETUP = true;
}
